#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: meson
# autospec version: v18
# autospec commit: a064a7f
#
Name     : gspell
Version  : 1.13.2
Release  : 31
URL      : https://download.gnome.org/sources/gspell/1.13/gspell-1.13.2.tar.xz
Source0  : https://download.gnome.org/sources/gspell/1.13/gspell-1.13.2.tar.xz
Summary  : No detailed summary available
Group    : Development/Tools
License  : LGPL-2.1
Requires: gspell-bin = %{version}-%{release}
Requires: gspell-data = %{version}-%{release}
Requires: gspell-lib = %{version}-%{release}
Requires: gspell-license = %{version}-%{release}
Requires: gspell-locales = %{version}-%{release}
BuildRequires : buildreq-gnome
BuildRequires : buildreq-meson
BuildRequires : docbook-xml
BuildRequires : libc6-locale
BuildRequires : pkgconfig(enchant-2)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
gspell - a spell-checking library for GTK applications
======================================================

%package bin
Summary: bin components for the gspell package.
Group: Binaries
Requires: gspell-data = %{version}-%{release}
Requires: gspell-license = %{version}-%{release}

%description bin
bin components for the gspell package.


%package data
Summary: data components for the gspell package.
Group: Data

%description data
data components for the gspell package.


%package dev
Summary: dev components for the gspell package.
Group: Development
Requires: gspell-lib = %{version}-%{release}
Requires: gspell-bin = %{version}-%{release}
Requires: gspell-data = %{version}-%{release}
Provides: gspell-devel = %{version}-%{release}
Requires: gspell = %{version}-%{release}

%description dev
dev components for the gspell package.


%package doc
Summary: doc components for the gspell package.
Group: Documentation

%description doc
doc components for the gspell package.


%package lib
Summary: lib components for the gspell package.
Group: Libraries
Requires: gspell-data = %{version}-%{release}
Requires: gspell-license = %{version}-%{release}

%description lib
lib components for the gspell package.


%package license
Summary: license components for the gspell package.
Group: Default

%description license
license components for the gspell package.


%package locales
Summary: locales components for the gspell package.
Group: Default

%description locales
locales components for the gspell package.


%package tests
Summary: tests components for the gspell package.
Group: Default
Requires: gspell = %{version}-%{release}

%description tests
tests components for the gspell package.


%prep
%setup -q -n gspell-1.13.2
cd %{_builddir}/gspell-1.13.2
pushd ..
cp -a gspell-1.13.2 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1725471162
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
meson --libdir=lib64 --prefix=/usr --buildtype=plain   builddir
ninja -v -C builddir
GOAMD64=v3
CFLAGS="$CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 " CXXFLAGS="$CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 " LDFLAGS="$LDFLAGS -march=x86-64-v3 " meson --libdir=lib64 --prefix=/usr --buildtype=plain   builddiravx2
ninja -v -C builddiravx2

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make check || :

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
mkdir -p %{buildroot}/usr/share/package-licenses/gspell
cp %{_builddir}/gspell-%{version}/LICENSES/LGPL-2.1-or-later.txt %{buildroot}/usr/share/package-licenses/gspell/5013d109e2fe11116d2b062bb46114a398276501 || :
GOAMD64=v3
DESTDIR=%{buildroot}-v3 ninja -C builddiravx2 install
GOAMD64=v2
DESTDIR=%{buildroot} ninja -C builddir install
%find_lang gspell-1
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/V3/usr/bin/gspell-app1
/usr/bin/gspell-app1

%files data
%defattr(-,root,root,-)
/usr/lib64/girepository-1.0/Gspell-1.typelib
/usr/share/gir-1.0/*.gir
/usr/share/vala/vapi/gspell-1.deps
/usr/share/vala/vapi/gspell-1.vapi

%files dev
%defattr(-,root,root,-)
/usr/include/gspell-1/gspell/gspell-checker-dialog.h
/usr/include/gspell-1/gspell/gspell-checker.h
/usr/include/gspell-1/gspell/gspell-entry-buffer.h
/usr/include/gspell-1/gspell/gspell-entry.h
/usr/include/gspell-1/gspell/gspell-enum-types.h
/usr/include/gspell-1/gspell/gspell-language-chooser-button.h
/usr/include/gspell-1/gspell/gspell-language-chooser-dialog.h
/usr/include/gspell-1/gspell/gspell-language-chooser.h
/usr/include/gspell-1/gspell/gspell-language.h
/usr/include/gspell-1/gspell/gspell-navigator-text-view.h
/usr/include/gspell-1/gspell/gspell-navigator.h
/usr/include/gspell-1/gspell/gspell-text-buffer.h
/usr/include/gspell-1/gspell/gspell-text-view.h
/usr/include/gspell-1/gspell/gspell.h
/usr/lib64/libgspell-1.so
/usr/lib64/pkgconfig/gspell-1.pc

%files doc
%defattr(0644,root,root,0755)
/usr/share/gtk-doc/html/gspell-1/GspellChecker.html
/usr/share/gtk-doc/html/gspell-1/GspellCheckerDialog.html
/usr/share/gtk-doc/html/gspell-1/GspellEntry.html
/usr/share/gtk-doc/html/gspell-1/GspellEntryBuffer.html
/usr/share/gtk-doc/html/gspell-1/GspellLanguage.html
/usr/share/gtk-doc/html/gspell-1/GspellLanguageChooser.html
/usr/share/gtk-doc/html/gspell-1/GspellLanguageChooserButton.html
/usr/share/gtk-doc/html/gspell-1/GspellLanguageChooserDialog.html
/usr/share/gtk-doc/html/gspell-1/GspellNavigator.html
/usr/share/gtk-doc/html/gspell-1/GspellNavigatorTextView.html
/usr/share/gtk-doc/html/gspell-1/GspellTextBuffer.html
/usr/share/gtk-doc/html/gspell-1/GspellTextView.html
/usr/share/gtk-doc/html/gspell-1/GtkEntry-support.html
/usr/share/gtk-doc/html/gspell-1/GtkTextView-support.html
/usr/share/gtk-doc/html/gspell-1/annexes.html
/usr/share/gtk-doc/html/gspell-1/annotation-glossary.html
/usr/share/gtk-doc/html/gspell-1/api-index-1-2.html
/usr/share/gtk-doc/html/gspell-1/api-index-1-4.html
/usr/share/gtk-doc/html/gspell-1/api-index-1-6.html
/usr/share/gtk-doc/html/gspell-1/api-index-full.html
/usr/share/gtk-doc/html/gspell-1/api-reference.html
/usr/share/gtk-doc/html/gspell-1/core-classes.html
/usr/share/gtk-doc/html/gspell-1/gspell-1.devhelp2
/usr/share/gtk-doc/html/gspell-1/home.png
/usr/share/gtk-doc/html/gspell-1/index.html
/usr/share/gtk-doc/html/gspell-1/intro.html
/usr/share/gtk-doc/html/gspell-1/language-choosers.html
/usr/share/gtk-doc/html/gspell-1/left-insensitive.png
/usr/share/gtk-doc/html/gspell-1/left.png
/usr/share/gtk-doc/html/gspell-1/object-tree.html
/usr/share/gtk-doc/html/gspell-1/right-insensitive.png
/usr/share/gtk-doc/html/gspell-1/right.png
/usr/share/gtk-doc/html/gspell-1/spell-checker-dialog.html
/usr/share/gtk-doc/html/gspell-1/style.css
/usr/share/gtk-doc/html/gspell-1/up-insensitive.png
/usr/share/gtk-doc/html/gspell-1/up.png

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/libgspell-1.so.3
/usr/lib64/libgspell-1.so.3

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/gspell/5013d109e2fe11116d2b062bb46114a398276501

%files tests
%defattr(-,root,root,-)
/V3/usr/libexec/installed-tests/gspell-1/test-checker
/V3/usr/libexec/installed-tests/gspell-1/test-entry
/V3/usr/libexec/installed-tests/gspell-1/test-icu
/V3/usr/libexec/installed-tests/gspell-1/test-inline-checker-text-buffer
/V3/usr/libexec/installed-tests/gspell-1/test-text-iter
/V3/usr/libexec/installed-tests/gspell-1/test-utils
/usr/libexec/installed-tests/gspell-1/test-checker
/usr/libexec/installed-tests/gspell-1/test-entry
/usr/libexec/installed-tests/gspell-1/test-icu
/usr/libexec/installed-tests/gspell-1/test-inline-checker-text-buffer
/usr/libexec/installed-tests/gspell-1/test-text-iter
/usr/libexec/installed-tests/gspell-1/test-utils
/usr/share/installed-tests/gspell-1/test-checker.test
/usr/share/installed-tests/gspell-1/test-entry.test
/usr/share/installed-tests/gspell-1/test-icu.test
/usr/share/installed-tests/gspell-1/test-inline-checker-text-buffer.test
/usr/share/installed-tests/gspell-1/test-text-iter.test
/usr/share/installed-tests/gspell-1/test-utils.test

%files locales -f gspell-1.lang
%defattr(-,root,root,-)

